server:
  port: 8082
spring:
  application:
    name: order-service # 作为服务发现的服务名
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848  # nacos 服务端地址
      discovery:
        username: nacos
        password: nacos
        namespace: fb09fef9-cafa-4d84-9961-544572027110 # dev环境
        ip: 127.0.0.1 # 客户端ip
        #        port: 8082 # 客户端port
        service: order-service # 客户端名称 ${spring.application.name}
        # 本地开发不使用 nacos
        register-enabled: false
        enabled: false
  devtools: # 配置热部署响应端口, 同时启动多应用, 端口一致会报错
    livereload:
      port: 35732
